apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
      - name: web
        image: localhost/test-web-app:v1
        ports:
        - containerPort: 80
