name: Deploy K8s App via GitOps

on:
  push:
    branches:
      - main
    #paths:
    #  - '**'

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "ci@github.com"

      - name: Confirm sync trigger
        run: echo "Change detected in K8s-gitops-demo, Argo CD will sync from Git."